# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Sf4xpi3YsYbqcEMYDg8z1WKA4pUw8aH
"""

#class and Object concept
class Student:

    # init method or constructor
    def __init__(self, name,rollNo):
        self.name = name
        self.rollNo=rollNo

    # Sample Method
    def show(self):
        print(self.rollNo,self.name)



p1 = Student('Nikhil',1)
p1.show()

p2=Student('Avantika',2)
p2.show()

p3=Student('Parvez',3)
p3.show()

p4=Student('Tanmay',4)
p4.show()

p5=Student('Sushant',5)
p5.show()

#Inheritance concept

class A:
  def run1():
    print('run1')
  def run2():
    print('run2')

class B(A):
  def walk1():
    print('walk1')
  def walk2():
    print('walk2')
r1=A
r1.run1()

r1.run2()

t1=B
t1.run1()
t1.run2()

#polymorphism concept

print(len('avantika'))
print(len(['avantika','parvez','tanmay']))

# print(add(5+5))
print('Avantika '+'Deshmukh')